### ISSUE TITLE
Problem with docker-compose 

### ISSUE THREAD

**Issue by AlessandroMinoccheri** [aws-samples/aws-dynamodb-examples#32]
I have an application developed with PHP, Nginx and dynamodb. I have create a simple docker-compose to work in local.

```
version: '3.7'

services:
  nginx_broadway_demo:
    container_name: nginx_broadway_demo
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./www:/var/www
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php_fpm_broadway_demo

  php_fpm_broadway_demo:
    container_name: php_fpm_broadway_demo
    build:
      context: ./docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/var/www/web

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    expose:
      - 8000
```

Now I need to add dynamodb URL params to allows PHP to make queries to the database. So, if I make a ping from PHP docker container like this works fine:

```
ping dynamodb
```
This doesn't work.

```
ping http://dynamodb:8000
```

I need to use http://dynamodb:8000 because AWS needs a URI because I have this error if I use http://dynamodb:8000:

Endpoints must be full URIs and include a scheme and host
So: how can I call a docker container like an URL? I have tried with docker-compose parameters like `depends`, `links`, `network` without success
